# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            '#!/bin/raykov'
tagline:          'to code or not to code...'
description:      'A developer blog about coding problems, life events and more'
url:              http://lyuboraykob.github.io/blog

author:
  name:           'Lyubomir Raykov'
  url:            http://lyuboraykov.com

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/lyboraykov/blog

baseurl:          https://lyuboraykov.github.io/blog
